# Permalinks
permalink:           pretty

# Setup
title:               Maker
tagline:             Whitepapers and general documentation
# url:
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Rune Christensen
  url:               https://twitter.com/mdo
  email:             rune@makedao.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/makerdao/docs

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist


markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
