# Permalinks
permalink:           none

# Setup
title:               Maker
tagline:             Whitepaper
url:                 http://makerdao.github.io/docs
paginate:            1
baseurl:             "http://makerdao.github.io/docs"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed




# navigation
navigation:

- title: Introduction to Maker
   url: /
 - title: DAI credit system
   url: /docs/dai-credit-system/
 - title: Keepers & Oracles
   url: /docs/keepers-and_oracles/
 - title: Governance & Decentralization
   url: /docs/governance-and-decentralization/

# About/contact
author:
  name:              Rune Christensen
  url:               https://twitter.com/makerdao
  email:             rune@makedao.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/makerdao/docs




markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]



gems:
  - jekyll-mentions
  - jekyll-sitemap
  - github-pages
  - jekyll-paginate
